config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :options
  resources :questions
  resources :assessments, only: [:new, :create, :show]

  root to: 'assessments#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  validates_presence_of :report_data

  def category_answers_hash
    question_categories = Question.questions_category_hash
    categories = {}

    question_categories.keys.each do |category|
      categories[category] = answers_hash(question_categories[category], self)
    end

    categories
  end

  private 

  def answers_hash(questions, obj)
    answers = {}

    questions.each do |question|
      option_id = obj.report_data[question[:id].to_s]
      option = Option.find(option_id)
      answers[question[:text]] = { text: option.text, hazards: option.hazards, image: option.image, question_id: question[:id] }
    end

    answers
  end
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question
  mount_uploader :image, ImageUploader

  default_scope { order(created_at: :asc) }
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :options, dependent: :delete_all
  accepts_nested_attributes_for :options, allow_destroy: true

  scope :by_category, -> (category) { where(category: category) }
  default_scope { order(created_at: :asc) }

  CATEGORIES = ["source", "pathway", "receptor"]

  def self.hash_with_options
    data = all.includes(:options)

    options_hash = {}

    data.map { |question| options_hash[question.text] = {id: question.id, type: question.view_type, options: question.options.map { |option| { id: option.id, text: option.text } }.flatten} }

    options_hash
  end

  def self.questions_category_hash
    hash = {}

    CATEGORIES.each do |category|
      hash[category] = Question.by_category(category).map{ |question| {id: question.id, text: question.text} }
    end

    hash
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :set_options_hash, only: %i[new]
  before_action :set_assessment, only: %i[show]

  def index; end

  def new; end

  def create
    assessment = Assessment.create(report_data: params[:assessment][:report_data])

    return redirect_to assessment_path(assessment) if assessment.persisted?
    render :new
  end

  def show
    return redirect_to '/' unless @assessment

    @answers_hash = @assessment.category_answers_hash
  end

  private

  def set_options_hash
    @options_hash = Question.hash_with_options
  end

  def set_assessment
    @assessment = Assessment.find_by(id: params[:id])
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_option, only: [:show, :edit, :update, :destroy]

  # GET /options
  # GET /options.json
  def index
    @options = Option.all
  end

  # GET /options/1
  # GET /options/1.json
  def show
  end

  # GET /options/new
  def new
    @option = Option.new
  end

  # GET /options/1/edit
  def edit
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(option_params)

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, notice: 'Option was successfully created.' }
        format.json { render :show, status: :created, location: @option }
      else
        format.html { render :new }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /options/1
  # PATCH/PUT /options/1.json
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { render :show, status: :ok, location: @option }
      else
        format.html { render :edit }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option.destroy
    respond_to do |format|
      format.html { redirect_to options_url, notice: 'Option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = Option.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def option_params
      params.require(:option).permit(:text)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @questions = Question.all
  end

  def show
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to questions_url, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:text, :category, options_attributes: [:id, :text, :hazards,:image, :_destroy])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active(action, controller)
    if params[:action] == action && params[:controller] == controller
      'selected'
    else
      nil
    end
  end
end

app/helpers/assessment_helper.rb
module AssessmentHelper
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/assessments/index.html.erb
<section class="hero">
    <div class="hero-content">
       <h1 class="hero-hadings">
         The aim of this tool is to help assessors to identify potential hazards associated with brownfield sites at preliminary risk asssessment stage.
       </h1>
       <h1 class="hero-hadings">
         In order to start the assessment, this tool requires background information on your site and its future use as inputs and produces a site report as output. The output will show the most likely hazards.       </h1>
       <h1 class="hero-hadings" style='margin-bottom: 4%;'>
          <br>Please click on the button below to start your site preliminary risk assessment
       </h1>

       <%= link_to 'Start your assessment!', new_assessment_path, class: 'navbar-brand button' %>
    </div>
</section>

app/views/assessments/new.html.erb
<h5 class="card-header info-color white-text text-center">
  <strong style='color:white'>NEW ASSESSMENT</strong>
</h5>

<div class="container">
  <div class="questions-area">
    <div class="row">
      <div class='col-xs-12 content-area'>
        <div class="working-content-area">
          <%= form_with url: assessments_path, method: :post do |f| %>
            <% @options_hash.keys.each do |key| %>
              <div class="form-group">
                <div class="row">
                  <div class="question-block">
                    <% if @options_hash[key][:type] == "dropdown" %>
                      <%= f.label key.to_sym, class: 'col-12 col-sm-5 normal-label' %>
                      <div class="col-12 col-sm-7">
                        <%= f.select("assessment[report_data][#{@options_hash[key][:id]}]", @options_hash[key][:options].map { |obj| [obj[:text], obj[:id]] }, { include_blank: 'Select an option' }, { class: 'form-control my-select', required: true }) %>
                      </div>
                    <% else %>
                      <%= f.label key.to_sym, class: 'col-sm-5 normal-label' %>
                      <div class="col-md-7 col-sm-7 printer-view radio-question">
                        <label class='custom-radio-check'>
                          <%= f.radio_button "assessment[report_data][#{@options_hash[key][:id]}]", @options_hash[key][:options].first[:id], required: true %>
                          <span class='checkmark'></span>
                          Yes
                        </label>

                        <div class="radio-false">
                          <label class='custom-radio-check'>
                            <%= f.radio_button "assessment[report_data][#{@options_hash[key][:id]}]", @options_hash[key][:options].second[:id], required: true %>
                            <span class='checkmark'></span>
                            No
                          </label>
                        </div>
                      </div>
                    <% end %>
                    <div class="clearfix"></div>
                  </div>
                </div>
              </div>
            <% end %>

            <div class='col-md-12 col-sm-11'>
              <div class="space-between">
                <%= f.submit 'Generate Report', class: "btn btn-main btn-large" %>
              </div>
            </div>
          <% end %>
       </div>
      </div>
    </div>
  </div>
</div>

app/views/assessments/show.html.erb
<div class="container show-container">
  <div class="row category-row">
    <div class="col-2 col-sm-2">
    </div>

    <div class="col-2 col-sm-2 category-col" data-category="source">
      Source
    </div>

    <div class="col-2 col-sm-2 category-col" data-category="pathway">
      Pathway
    </div>

    <div class="col-2 col-sm-2 category-col" data-category="receptor">
      Receptor
    </div>

    <div class="col col-sm">
    </div>
  </div>

  <div class="row align-items-center">
    <div class="col-3 col-md-3">
      <% @answers_hash.keys.each_with_index do |category, category_index| %>
        <% @answers_hash[category].keys.each_with_index do |question, question_index| %>
          <div class="row">
            <div class="col-md-12 <%= category %> category-btn">
              <a class="button btn btn-primary btn-tab question_<%= category_index %>_<%= question_index %>" data-toggle="collapse" href="#collapse-card" role="button" aria-expanded="false" aria-controls="collapseExample">
                  <%= question %>
              </a>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="col-9 col-md-9 answer-sec">
      <div class="collapse" id="collapse-card">
        <% @answers_hash.keys.each_with_index do |category, category_index| %>
          <% @answers_hash[category].keys.each_with_index do |question, question_index| %>
            <div class=" p-7 mb-7 bg-white rounded ">
              <div class="  answer_<%= category_index %>_<%= question_index %> d-none answers answer-card">
                <h5 class="card-header info-color white-text text-center">
                  <strong style='color:white'><%= question %></strong>
                </h5>
                <div class="row answer-row selection">
                  You have picked &nbsp<strong style='color:black'><%= @answers_hash[category][question][:text] %></strong>
                  <% if @answers_hash[category][question][:text] == "All" %>
                    <% opts = Question.find_by(id: @answers_hash[category][question][:question_id])&.options.pluck(:text) - ['All', 'None'] %>
                    <strong>(<%= opts.join(", ") %>)</strong>
                  <% end %>
                </div>

                <% if @answers_hash[category][question][:text] == "All" %>
                  <% Question.find_by(id: @answers_hash[category][question][:question_id])&.options.each do |option| %>
                    <% if option.text != "None" && option.text != "All" %>
                      <div class="row answer-row">
                        <%= option.hazards %>
                      </div>

                      <div class="row mt-5">
                        <%= image_tag(option.image.to_s, class: 'option-image') if option.image.present? %>
                      </div>
                    <% end %>
                  <% end %>
                <% else %>
                  <div class="row answer-row">
                    <%= @answers_hash[category][question][:hazards] %>
                  </div>

                  <div class="row mt-5">
                    <%= image_tag(@answers_hash[category][question][:image].to_s, class: 'option-image') if @answers_hash[category][question][:image].present? %>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-mainbg">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fas fa-bars text-white"></i>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
          <li class="nav-item <%=is_active('index', 'assessments')%> ">
              <a class="nav-link" href="/"><i class="fas fa-home"></i>Home</a>
          </li>
          <li class="<%=is_active('new', 'assessments')%> nav-item">
              <a class="nav-link" href="/assessments/new"><i class="far fa-address-book"></i>New Assessment</a>
          </li>
          <% if !current_user %>
            <li class="<%=is_active('new', 'devise/sessions')%> nav-item">
                <a class="nav-link" href="/users/sign_in"><i class="fa fa-user"></i>Log in</a>
            </li>
          <% else %>
            <li class="<%=is_active('index', 'questions')%> nav-item">
                <a class="nav-link" href="/questions"><i class="fa fa-cogs"></i>Manage Questions</a>
            </li>
            <li class="<%=is_active('index', 'questions')%> nav-item">
                <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
            </li>
          <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Construction</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/options/_form.html.erb
<%= form_with(model: option, local: true) do |form| %>
  <% if option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
        <% option.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/options/edit.html.erb
<h1>Editing Option</h1>

<%= render 'form', option: @option %>

<%= link_to 'Show', @option %> |
<%= link_to 'Back', options_path %>

app/views/options/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Options</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @options.each do |option| %>
      <tr>
        <td><%= option.text %></td>
        <td><%= link_to 'Show', option %></td>
        <td><%= link_to 'Edit', edit_option_path(option) %></td>
        <td><%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Option', new_option_path %>

app/views/options/new.html.erb
<h1>New Option</h1>

<%= render 'form', option: @option %>

<%= link_to 'Back', options_path %>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @option.text %>
</p>

<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>

app/views/questions/_form.html.erb
<h5 class="card-header info-color white-text text-center py-4">
  <strong style='color:white'>EDIT OPTIONS OF THE QUESTION</strong>
</h5>
<div class="container" style='margin-bottom:5%;'>
  <div class="row">
      <div class="col-md-12">
        <div class="well well-sm">
          <%= semantic_form_for @question do |form| %>
            <% if question.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>
                <ul>
                  <% question.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="form-group" style='margin-top:4%'>
              <label for="text" style='color:#0289C3'>Question Text:</label>
              <%= form.text_field :text, :class =>'form-control', id: 'text'%>
            </div>
            <div class="form-group">
              <h3 for="text" style='color:#0289C3'>All options</h3>
            </div>
            <%= form.semantic_fields_for :options do |option| %>
              <%= render 'option_fields', :f => option %>
            <% end %>
          <nav class="navbar fixed-bottom navbar-light bg-light">
            <%= form.submit 'Update question', :class => 'navbar-brand button' %>
            <%= link_to 'Back', questions_path, class: 'navbar-brand button' %>
            <%= link_to_add_association 'Add another option', form, :options, class: 'navbar-brand button'%>
          </nav>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/questions/_option_fields.html.erb
<div class='nested-fields'>
  <%= f.inputs do %>
    <div class='row'>
      <div class="col">
        <div class="float-right">
            <%= link_to_remove_association button_tag('x', type: "button", class: 'remove-option'), f %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <label for="text">Option name:</label>
      <%= f.text_field :text, :class =>'form-control', id: 'text'%>
    </div>
    <div class="form-group">
      <label for="email">Description:</label>
      <%= f.text_area :hazards, :class =>'form-control', cols:"25", rows:"10"%>
    </div>
    <div class="form-group">
        <% if f.object.image.to_s.empty? %>
          <label for="email">Image:</label>
          <%= f.file_field :image, label: "Upload a founder photo.", class: 'form-control' %>
        <% else %>
          <label for="email">Replace image:</label>
          <%= f.file_field :image, label: "Upload a founder photo.", class: 'form-control' %>
          <%= image_tag f.object.image.to_s, accept: 'image/png, image/jpeg', style: 'height:50%;width:50%; margin: 3%; margin-left:25%;', class: 'form-control'%>
        <% end %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h5 class="card-header info-color white-text text-center py-4">
  <strong style='color:white'>ALL QUESTIONS</strong>
</h5>
<div style='margin-bottom:5%;'>
  <div class="row">
      <div class="col-md-12">
        <div class="well well-sm">
          <table class="table table-striped custab">
            <thead>
              <tr>
                <th>Question Text</th>
                <th>Category</th>
                <th>No. of options</th>
                <th class="text-center">Manage</th>
              </tr>
            </thead>
            <% @questions.each do |question| %>
              <tr>
                <td><%= question.text %></td>
                <td><%= question.category %></td>
                <td><%= question.options.count %></td>
                <td class="text-center">
                  <%= link_to edit_question_path(question) do %>
                    <i class="fa fa-cogs"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @question.text %>
</p>

<p>
  <strong>Category:</strong>
  <%= @question.category %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>